apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-gui
  template:
    metadata:
      labels:
        app: contacts-gui
    spec:
      containers:
        - image: ghcr.io/openline-ai/openline-contacts:latest
          name: contacts-gui
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: http-port
