apiVersion: apps/v1
kind: Service
metadata:
  name: contacts-gui-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: contacts-gui